### ISSUE TITLE
Issue#6 Answer the question : Distinguish querySelector 

### ISSUE THREAD

**Issue by TheHienDuong** [Agility-Internship/Duong-The-Hien-Javascript#39]
### Question

> Distinguish querySelector by id, by class, by name, by tag, by css property. How should use each query correctly, optimally, and for what use case?

**Comment by TheHienDuong** [comment]
### My Answer:
`querySelector` is a method that returns the first element within the document that matches the specified selector or group of selectors. Use it to select elements by their **id**, **class** , **name**, **tag**, or **css property**.

- **By ID**: Use a hash symbol (#) followed by the id value.

> For example: `document.querySelector('#myId')`

- **By class**: Use a period (.) followed by the class value. 

> For example: `document.querySelector('.myClass')`

- **By name**: Use square brackets ([]) with the attribute name and value. 

> For example: `document.querySelector('[name="myName"]')`

- **By tag**: Use the tag name directly. 

> For example: `document.querySelector('div')`

- **By css property**: Use square brackets ([]) with the attribute name and value.

> For example: `document.querySelector('[style="color: red;"]')`

Should choose the most specific selector that matches your needs to optimize performance. For example, If you want to select an element with a unique id, using the id selector would be the most efficient.

**Comment by phattruong-agilityio** [comment]
Please more detail on this answer: "Should choose the most specific selector that matches your needs to optimize performance.". You can get from your practice to make the example!

**Comment by TheHienDuong** [comment]
> Please more detail on this answer: "Should choose the most specific selector that matches your needs to optimize performance.". You can get from your practice to make the example!

- Since querySelector is the method that returns the first element in the document that matches the selector, in some cases if we only get the class, name , tag and css properties, sometimes there will be some duplicate parts, so when use queySelector for the above selectors then they only take the first element that matches the selector. So the most optimal and to avoid duplicate selectors, we should use id for querySelector, because according to the rule id is defined by only once in a web structure
For example in my practice-01 :

```html structure of a div tag with form-group for multiple labels
            <div class="form-group">
                <label for="fullname" class="form-label">Name*</label>
                <input id="fullname" name="fullname" type="text" placeholder="Enter your name" class="form-control" />
                <span class="form-message"></span>
            </div>
            <!-- Email -->
            <div class="form-group">
                <label for="email" class="form-label">Email*</label>
                <input id="email" name="email" type="text" placeholder="Enter your email" class="form-control" />
                <span class="form-message"></span>
            </div>
            <!-- Age -->
            <div class="form-group">
                <label for="age" class="form-label">Age*</label>
                <input id="age" name="age" type="number" placeholder="Enter your age" class="form-control" />
                <span class="form-message"></span>
            </div>
```

**Comment by TheHienDuong** [comment]
-  #40 

> _In my internal review on friday, after receiving comments on this issue and doing some more google searching, here's an update to my recently hit answer on this issue._

---------------------------------------------------------------

### Results

- **By ID:**  The id is a unique attribute of the HTML element and can only be used once on a page. You should use id when you want to manipulate a unique element on your web page. 
>-  With an id selector (#myId) is the most efficient way to select a unique element with a specific id. Since ids are unique, this method returns the element immediately without having to search the entire document.

- **By class:**  Is useful if you want to select the first element with a specific class. You should use class when you want to apply the same formatting or behavior to multiple elements on your website.
> - Combine querySelector with other methods like` classList.add`, `classList.remove` and `classList.toggle` to manipulate the class of elements.
> - You can use querySelector with the class in a variety of situations, such as to format a specific element on your web page, to add an event for a specific link, or to hide or show an element. specifically.

- **By tag:** You should use tag when you want to manipulate all elements with the same tag name on your website.

- **By name:** The name attribute is commonly used in form elements such as input, select, and textarea to identify the name of the data being sent when the form is submitted.

- **By css property:** You can use CSS properties in CSS selectors to select elements based on the value of their CSS properties. However, this usage is not common and not recommended as it can cause errors and be difficult to maintain.

_In general, it’s important to use the most specific selector possible to optimize the performance of your queries. For example, if you know that the element you want to select has a unique id, using an id selector would be the most efficient way. If you’re not sure which selector to use, you can experiment and see which one gives you the best performance._
