### ISSUE TITLE
Practice-01: NOTE

### ISSUE THREAD

**Issue by TheHienDuong** [Agility-Internship/Duong-The-Hien-Javascript#43]
## OVERVIEW
_**This is the place to save the issues encountered during practice-01, what have been learned**_
### Learned
-  == vs ===
- Apply [CallStack]( https://developer.mozilla.org/en-US/docs/Glossary/Call_stack)
- #31
>  Code format 
- Using MARKDOWN in git
- #5 
> Push resulst in Array, use alert show results
- #2 Question 1 
> Apply  Truthy/Falsy in conditional statement
- Form submit , form field.
- Attributes, Classes, and CSS Manipulation.
- **_DOM manipulation_**
> Querying/Modifying DOM
DOMEevent listener

### List of issues

-  **_Uppercase for comments in .html_**

> https://github.com/Agility-Internship/Duong-The-Hien-Javascript/pull/11 [Fix: Update uppercase frist character & type-submit](https://github.com/Agility-Internship/Duong-The-Hien-Javascript/pull/11/commits/b80166c8646bdd059b5e4d8dc06259d8288faa19)

- #17 
> **Common problems:** Naming  for function; Wrong branch name; js code in html file
- #20 
> **Common problems:** Code style, split lines; format comment function
- #24 &&  #25 
>**Common problems:** function name; comment function; redundant code; comment line; capitalize the first character
- #38 
- #39 
- #40
### OTHER
- #42 
> List things to double check before submitting results (push code, submit pull request, comments, ...)
- #27 
> Create a template for creating a new task# in github

**Comment by phattruong-agilityio** [comment]
Look good to me
