### ISSUE TITLE
Issue#1: About comments in PR#64 - Task#8 Add filter for manufacturer logos 

### ISSUE THREAD

**Issue by TheHienDuong** [Agility-Internship/Duong-The-Hien-Javascript#65]
- #57 
PR:  #64
### DESCRIPTION
In the last 2 comments, i have some issues that have not been resolved

              why get `name` from img, can we get it right on the click button ?

_Originally posted by @phattruong-agilityio in https://github.com/Agility-Internship/Duong-The-Hien-Javascript/pull/64#discussion_r1226044987_

------
              I think I can select multiple products brand, so please make it correct

_Originally posted by @phattruong-agilityio in https://github.com/Agility-Internship/Duong-The-Hien-Javascript/pull/64#discussion_r1226045304_

### MY ISSUES

- [x] Question 1: About getting 'name' from img, because img tag is in tag button so want to filter by name I need to get name in img tag, tried using many ways but still failed. Please give me suggestions on this matter.

---

- [x] Question 2: About the product display problem when clicking the logo button 
1.CODE
```
    logoButtons.forEach(function (button) {
        button.addEventListener('click', function () {
            const nameProduct = button.querySelector('img').getAttribute('name');
            const filteredProducts = filterProductsByName(myJson, nameProduct);

            if (button.classList.contains('selected')) {
                // Deselect the product
                selectedProducts = selectedProducts.filter(product => product.name !== nameProduct);
                button.classList.remove('selected');
            } else {
                // Select the product
                selectedProducts.push(...filteredProducts);
                button.classList.add('selected');
            }

            renderProductsCard(selectedProducts);
        });
    });
``` 
2.DEMO

https://github.com/Agility-Internship/Duong-The-Hien-Javascript/assets/113186169/6ff27419-9d3c-4103-9301-946beeafb3e0

- This is my thinking:
> If the button already has the class selected, it means that the product is currently selected. In this case, the code removes the product from the selectedProducts array by filtering out the product with a matching name. It also removes the selected class from the button.
> If the button does not have the class selected, it means that the product is not selected. In this case, the code adds the filtered products (obtained from filterProductsByName) to the selectedProducts array using the spread operator (...). It also adds the selected class to the button.

**But Users can click on multiple logos to display the required phone list. But when the user clicks the button again times, nothing happens, the product is still there, and if you click it again, the product will be duplicated. This is the problem I'm having**

**Comment by phattruong-agilityio** [comment]
Question#1: Please try this solutions, you do like this `<button value="apple">`, 
you can get value right on button `event` object

```js

button.addEventListener('click', function (event) {  ...  }) <==== get selected brand right on event object
```

**Comment by TheHienDuong** [comment]
Qestion#2: data.filter(item => selectedBrands.include(item.name))

**Comment by TheHienDuong** [comment]
**_Question#2: Resolved after feedback from the mentor, here are the notes on how to solve the above problem_**
#### NOTE
1. It filters the "myJson" array of products based on the "nameProduct" using the "filterProductsByName" function. The filtered products are assigned to the variable "filteredProducts".
2. If the clicked button does not have the class "selected":
   - It adds the class "selected" to the clicked button.
   - It appends the filtered products to the "selectedProducts" array using the spread operator.
3. If the clicked button has the class "selected":
   - It removes the class "selected" from the clicked button.
   - It removes the filtered products from the "selectedProducts" array using the "filter" method.
4. It checks if there are any selected products in the "selectedProducts" array.
   - If there are selected products, it calls the "renderProductsCard" function with the "selectedProducts" array as an argument.
   - If there are no selected products, it calls the "renderProductsCard" function with the original "myJson" array as an argument.

_**Use data.filter(item => Selected Brands.include(item.name)) to filter and Remove the products does not have class 'selected' ra khỏi mảng selectecedBrand**_
